### PR TITLE
Fix cache announcer

### PR DESCRIPTION
**Pull request by mhqz**
This PR increases the number of BEP5 announcement attempts processed at the same time in `cache.Announcer::Loop::loop`. The new mechanism spawns a limited number of co-routines that is defined by a new setting named `max-simultaneous-announcements`.

Additionally to the test included in this patch, I've successfully tested it with Ouicrawl to inject several entries to the distributed cache and managed to increase the number of announcements from 100 (before patching Ouinet) to 500 using a batch size of 16 announcements per iteration. It's important to mention that those entries were also re-announced as expected during the period of the tests (24 hours).

Please let me know if you have any questions or suggestions.

### CODE REVIEW

**Comment by paidforby** [comment]
The changes make sense to me. One point of clarification, you mention
> managed to increase the number of announcements from 100 (before patching Ouinet) to 500 using a batch size of 16 announcements per iteration
Are the number of announcements per a time frame? Or does this mean that ouinet only supports announcing up to 500 groups and after that point we see the same failures we saw before the patch at around 100 groups? I guess I just want to understand if this the full solution or just a partial solution.

**Comment by mhqz** [comment]
> Or does this mean that ouinet only supports announcing up to 500 groups and after that point we see the same failures we saw before the patch at around 100 groups?

What I mean is that a Ouinet client is stable when announcing 500 groups in batches of 16 (running in a relatively small VPS 2 vCPUs and 4GB of RAM) for a long period of time (24 hours).

The success rate of announcements starts to decrease if you announce more than 500 groups but only for this particular setup, so with more computing resources the number of simultaneous announcements could be increased to achieve more announcements until we face another kind of bottlenecks (like the network or possible rate limiting of DHT peers).

I'm planning to do more testing with different batch sizes and also to play a bit with the re-announcing periods but I think that should be part of a different PR.

**Comment by mhqz** [comment]
>  I guess I just want to understand if this the full solution or just a partial solution.

Considering that we're playing here not only with the performance of the Ouinet client but with the limits that different BT clients establish for their own interactions with the DHT, I'd say that this is probably just a good improvement that bring us closer to an arbitrary goal of 10k announcements per client (which I think would be acceptable for Ouicrawl use case :smile_cat: )

**Comment by inetic** [comment]
You don't want to exit [here](https://github.com/equalitie/ouinet/pull/59/files#diff-10ed8d574a0303200ff325fb684f67eea3e24154d203c3d2b6c37dc468d00683R292) if the `cancel` that is passed to the `loop` function is invoked before the coroutines are finished. So I would just invoke the [`wait` version without `cancel` parameter`](https://github.com/equalitie/ouinet/blob/43798686764237ff405d4c46a42286cca936dd51/src/util/wait_condition.h#L68) there.

Failing to do that may cause memory leaks because the [coroutine lambdas](https://github.com/equalitie/ouinet/pull/59/files#diff-10ed8d574a0303200ff325fb684f67eea3e24154d203c3d2b6c37dc468d00683R259) capture their context with the `&` and once you leave the `loop` function the coroutines may still work and try to access whatever they capture (e.g. `this`, which may be destroyed right after the `loop` function ends).

Above you mention

> and now the client is much more stable when the number of announcements goes beyond one thousand.

but you did not mention instability before. Are there still stability issues?

**Comment by mhqz** [comment]
Hi @inetic, thanks a lot for you feedback :metal:, I've modified the call to the `wait` method as you suggested, tested the client with batches of 64 and everything seems normal (the tests performed  512 announcements in ~7 minutes).

> but you did not mention instability before. Are there still stability issues?

There is an error that happens from time to time when stressing the Ouinet client (e.g. when announcing more than 1000 groups, with 2 ouicrawl instances adding more entries at the same time than serving cached pages via uTP at a rate of 1.5 per second):

```
[INFO] C1587/R11311/mixed_fetch/injector_or_dcache/cc_fetch Fetch fresh failed to stop
client: /tmp/tmp.mcFwtT4Msl/src/cache_control.cpp:261: ouinet::CacheControl::do_fetch(const Request&, const boost::optional<std::__cxx11::basic_string<char> >&, boost::system::error_code&, boost::system::error_code&, ouinet::Cancel&, ouinet::Yield)::<lambda()>::<lambda()>: Assertion `0' failed.
Aborted
``` 
As this error seems to be happening when the `do_fetch` fails to cancel, I assume that it could be related to the potential leak that you found.

I'll repeat the tests with the patched client and will compare it with my previous results.

**Comment by mhqz** [comment]
The tests of the patched Ouinet client are working fine; I managed to announce 1500 of groups in batches of 64.

I think the fix is stable enough to release it, I'll merge it to master so we can start using it in our Ouicrawl environment and will continue working on more improvements in a separate branch.

**Pull request merged**
